Error handling in ff.

diff --git a/bin/ff b/bin/ff
--- a/bin/ff
+++ b/bin/ff
@@ -1,3 +1,8 @@
 #!/bin/bash
 
+if [ -z $1 ]; then
+	echo "Search argument required. Eg. ff search_string."
+	exit 1
+fi
+
 find . -type f -exec grep -i -l $1 {} \;
